export const typewriterText = [
  "Software Engineer",
  "Full-Stack Developer",
  "Data Engineer",
  "Co-Founder",
  "Tech Enthusiast",
  "Music Nerd",
  "Nature Lover",
];

export const experiences = [
  {
    date: "September 2023 - Present",
    logo: "/assets/img/logos/carleton.jpg",
    company: "Carleton University",
    role: "Undergraduate Teaching Assistant",
    desc: "TA in computer science and math/statistics department, teaching introductory computer science and statistical modelling courses; co-developed course content, led reviews, and managed online platforms to support student learning.",
  },
  {
    date: "May 2023 - August 2023",
    logo: "/assets/img/logos/kinaxis.png",
    company: "Kinaxis",
    role: "Software Developer Intern",
    desc: "Contributed to RapidResponse's next-gen client, migrating legacy Java features to web, optimizing APIs for 26% front-end-server interaction speedup, and implementing ReactJS/TS front-end functionalities.",
  },
  {
    date: "September 2022 - December 2022",
    logo: "/assets/img/logos/pilot.png",
    company: "Pilot",
    role: "Software Engineer Intern",
    desc: "Developing and maintaining Pilot flight planner's front-end, implementing multiple key React features, fixing issues. Configured analytics tools and CI/CD environment with Google Cloud Platform for decision-making and growth.",
  },
  {
    date: "June 2023 - Present",
    logo: "/assets/img/logos/cublueprint.jpg",
    company: "CU Blueprint",
    role: "Engineering Project Manager",
    desc: "Led software development for social change, collaborating with stakeholders to translate requirements into actionable plans. Managed resources, implemented tools, and facilitated communication for successful project delivery.",
  },
  {
    date: "2023 - Present",
    logo: "/assets/img/logos/inertia.png",
    company: "Inertia",
    role: "Co-Founder; Technical Lead and Product Manager",
    desc: "Co-founded and led Inertia as business director and technical product manager. Led development, designed and implemented software products, systems, and website. Drove marketing and branding initiatives through multiple channels.",
  },
  {
    date: "May 2022 - August 2022",
    logo: "/assets/img/logos/gaotek.png",
    company: "GAOTek Inc.",
    role: "Embedded Software Engineer Intern",
    desc: "Contributed to events management software, developer experience platform, and backend admin platforms. Supported troubleshooting and worked on embedded systems using C, C++, Java, and Python in various capacities.",
  },
  {
    date: "February 2022 - May 2022",
    logo: "/assets/img/logos/digitera.png",
    company: "Digitera Interactive",
    role: "Software Developer Intern",
    desc: "Pioneered suite of employer-focused screening tools as sole developer with LAMP Stack, cutting candidate evaluation time by 50% and boosting successful hires by 30%. Orchestrated automated testing, reducing bugs by 35%.",
  },
  {
    date: "2018 - 2020",
    logo: "/assets/img/logos/sweetme.jpg",
    company: "Sweet Me",
    role: "Full Stack Developer / Digital Product Manager",
    desc: "Developed a flexible administrative system to enhance business flow. Managed online and social media presence. Handled marketing, vendor management, supply chain organization, and budgeting; improved purchase processing speed by over 60%.",
  },
  {
    date: "2020 - 2022",
    logo: "/assets/img/logos/freelance.png",
    company: "Freelance Developer / Open Source Contributor",
    role: "",
    desc: "Developed, optimized, and worked on several websites and applications. Collaborated with clients, managed large codebases, conducted testing, and stayed updated with industry trends. Made frequent open-source community contributions.",
  },
];

export const projects = [
  {
    name: "Chloe AI Assistant",
    desc: "AI Virtual Assistant, based on the GPT-3 Model by OpenAI, allowing it to make use of one of the most powerful AI models to respond to almost any query. Takes in user input using Whisper, and returns a text, and tts response from Chat-GPT!",
    ghLink: "https://github.com/OmarAnwar19/Chloe-AI-Virtual-Assistant",
    showDemo: false,
    demoLink: "#",
  },
  {
    name: "Nine Worlds Chat",
    desc: "A full-stack chat app which connects users for worldwide communication!",
    ghLink: "https://github.com/OmarAnwar19/Chat-App-With-User-Authentication",
    showDemo: false,
    demoLink: "#",
  },
  {
    name: "Pilot Weather",
    desc: "Keep up to date with the latest weather conditions using this react app!",
    ghLink: "https://github.com/OmarAnwar19/Pilot-Weather",
    showDemo: false,
    demoLink: "#",
  },
  {
    name: "LSTM / RF Stocks Forecasting and Dashboard",
    desc: "A machine learning-based stock prediction and analysis project that utilizes Random Forest and LSTM models to predict stock movements and future prices, respectively; includes a dynamic dashboard that provides valuable insights into stock data as-well as Prophet forecasts.",
    ghLink:
      "https://github.com/OmarAnwar19/LSTM-RF-Stocks-Forecasting-Dashboard",
    showDemo: false,
    demoLink: "#",
  },
  {
    name: "A* Visualizer",
    desc: "Visualizer for the A* algorithm for path-finding between two points!",
    ghLink:
      "https://github.com/OmarAnwar19/A-Star-Path-Finding-Algorithim-Visualizer",
    showDemo: false,
    demoLink: "#",
  },
  {
    name: "19tracks",
    desc: "My personal music blog, where I spill my thoughts about all things music!",
    ghLink: "https://github.com/OmarAnwar19/19tracks",
    showDemo: true,
    demoLink: "https://www.19tracks.tk/",
  },
  {
    name: "NFT Generator",
    desc: "Generate hundreds of thousands of random NFT's using Python!",
    ghLink: "https://github.com/OmarAnwar19/NFT-Generator",
    showDemo: false,
    demoLink: "#",
  },
  {
    name: "Facebook Clone",
    desc: "A functional clone of the facebook web app front-end, emulating the experience of the Facebook web app, allowing for responsive design, and a comfortable user experience!",
    ghLink: "https://github.com/OmarAnwar19/Facebook-Clone",
    showDemo: false,
    demoLink: "#",
  },
  {
    name: "Portfolio V2",
    desc: "The new version of my portfolio, the one your looking at right now!",
    ghLink: "https://github.com/OmarAnwar19/Portfolio-v2",
    showDemo: false,
    demoLink: "#",
  },
  {
    name: "React PokeDex",
    desc: "A fun comprehensive PokeDex, made using ReactJs, and PokeAPI!",
    ghLink: "https://github.com/OmarAnwar19/React-PokeDex",
    showDemo: false,
    demoLink: "#",
  },
  {
    name: "NBA Data Analysis",
    desc: "A data analysis project on the past 10 NBA seasons. Scraping, cleaning, analyzing, and visualizing data. Exploring player, team, and game statistics, as well as different metrics and changes over the years!",
    ghLink: "https://github.com/OmarAnwar19/NBA-Data-Analysis",
    showDemo: false,
    demoLink: "#",
  },
];
